### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by PureTryOut** [pavelmachek/unicsy_demo#3]
Python 2 is reaching EOL in January, and Alpine Linux is dropping Python 2 support in time for Alpine Linux 3.11 (the next release) so this package won't be usable anymore without a port to Python 3.

**Comment by z3ntu** [comment]
Suggestions:
* Format all your code with autopep8 (`autopep8 -i --ignore E402 *all-your-python-files*`) (ignore E402 because that would change the import order which breaks things in this case)
* Convert the pygtk code according to https://pygobject.readthedocs.io/en/latest/guide/porting.html (https://gitlab.gnome.org/GNOME/pygobject/raw/master/tools/pygi-convert.sh)
* Convert some instances of Python2 code with 2to3
* Change the shebang of the files from python2 to python3 when it's all working
* Install the lib files properly using a setup.py script to get rid of the sys.path hacks
* Install the executables that you want properly (demo/about demo/tefone hacks/keyd monitor/batmond monitor/mond ofone/ofone), prefix them with maybe unicsy or something.

**Comment by pavelmachek** [comment]
Hehe. Fun. I had python3 version working at some point, but it needs more RAM and is slower, which is and issue on N900. My goal is to have code running under both Python 2 and 3, but I won't switch for now for performance reasons.
